#!/bin/sh -e

PKG="canaima-estilo-visual"
ARCHIVOS="/etc/grub.d/10_linux \
/etc/grub.d/05_debian_theme \
/usr/lib/mime/packages/openoffice.org-writer \
/usr/lib/mime/packages/openoffice.org-calc \
/usr/lib/mime/packages/openoffice.org-impress \
/usr/share/applications/amsn.desktop \
/usr/share/applications/freemind.desktop \
/usr/share/applications/htop.desktop \
/usr/share/applications/openoffice.org-draw.desktop \
/usr/share/applications/openoffice.org-writer.desktop \
/usr/share/applications/scribus.desktop \
/usr/share/applications/vlc.desktop \
/usr/share/applications/cheese.desktop \
/usr/share/applications/gnome-btdownload.desktop \
/usr/share/applications/nm-connection-editor.desktop \
/usr/share/applications/openoffice.org-impress.desktop \
/usr/share/applications/openproj.desktop \
/usr/share/applications/system-config-printer.desktop \
/usr/share/applications/winecfg.desktop \
/usr/share/applications/dia-common.desktop \
/usr/share/applications/gparted.desktop \
/usr/share/applications/openoffice.org-base.desktop \
/usr/share/applications/openoffice.org-math.desktop \
/usr/share/applications/pidgin.desktop \
/usr/share/applications/thunderbird.desktop \
/usr/share/applications/xscreensaver.desktop \
/usr/share/applications/ekiga.desktop \
/usr/share/applications/gtkpod.desktop \
/usr/share/applications/openoffice.org-calc.desktop \
/usr/share/applications/openoffice.org-startcenter.desktop \
/usr/share/applications/planner.desktop \
/usr/share/applications/uninstaller.desktop"

case "$1" in
  upgrade)
    for archivo in ${ARCHIVOS}

    do
	if [ -e $archivo ] 
	then
	      BASE=`basename $archivo`
	      dpkg-divert --package $PKG --remove --rename \
	                  --divert /var/lib/$PKG/diverts/$BASE $archivo
	fi
    done


  ;;
esac
