#!/bin/bash -e
#
# ==============================================================================
# PAQUETE: canaima-estilo-visual
# ARCHIVO: preinst
# DESCRIPCIÓN: Configura el sistema antes de la instalación del paquete.
# COPYRIGHT:
#  (C) 2010 Luis Alejandro Martínez Faneyth <martinez.faneyth@gmail.com>
#  (C) 2010 Diego Alberto Aguilera Zambrano <daguilera85@gmail.com>
#  (C) 2010 Carlos Alejandro Guerrero Mora <guerrerocarlos@gmail.com>
#  (C) 2010 Francisco Javier Vásquez Guerrero <franjvasquezg@gmail.com>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

PKG="canaima-estilo-visual"
21_QUITAR="/etc/grub.d/05_debian_theme /etc/grub.d/10_linux /usr/lib/mime/packages/openoffice.org-calc /usr/lib/mime/packages/openoffice.org-impress /usr/lib/mime/packages/openoffice.org-writer /usr/share/themes/Clearlooks /usr/share/splashy /usr/share/doc/canaima-estilo-visual /usr/share/canaima-estilo-visual /usr/share/gconf/defaults/90_canaima*"

# Color Verde
VERDE="\e[1;32m"
# Color Rojo
ROJO="\e[1;31m"
# Color Amarillo
AMARILLO="\e[1;33m"
# Negrita
BOLD="\e[1m"
# Caracter de fin de línea
FIN="\e[0m"

function ERROR() {
echo -e ${ROJO}${1}${FIN}
exit 1
}

function ADVERTENCIA() {
echo -e ${AMARILLO}${1}${FIN}
}

function EXITO() {
echo -e ${VERDE}${1}${FIN}
}

case ${1} in

        install|upgrade)


                # ---- Limpieza de configuraciones anteriores y residuos de Canaima 2.1 ------------------------------------#
                # ==========================================================================================================#

		if [ "$(dpkg-query -s ${PKG} | grep Status)" == "Status: install ok installed" ] && [ "$(dpkg-query -s ${PKG} | grep 'Version: 2.')" != '' ]; then
			ADVERTENCIA "Removiendo diverts de Canaima 2.1"
			dpkg-divert --package ${PKG} --remove --rename --divert /var/lib/${PKG}/diverts/gtkrc /usr/share/themes/Clearlooks/gtk-2.0/gtkrc
			dpkg-divert --package ${PKG} --remove --rename --divert /var/lib/${PKG}/diverts/grub /etc/default/grub

			ADVERTENCIA "Limpiando configuraciones obsoletas de Canaima 2.1"
			for LIMPIEZA in ${21_QUITAR}; do
				rm -rf ${LIMPIEZA}
				echo "Removiendo ${LIMPIEZA} ..."
			done    
		fi
	;;

        abort-upgrade)
        ;;

        *)
                ERROR "preinst no reconoce el argumento '"${1}"'" >&2
                exit 1
        ;;

esac

#DEBHELPER#

exit 0
